name: marquee
description: 'A Flutter widget that scrolls text infinitely. Provides many
  customizations including custom scroll directions, durations, curves as well
  as pauses after every round.'
version: 2.2.3
repository: https://github.com/MarcelGarus/marquee

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  fading_edge_scrollview: ^4.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
